apiVersion: v1
kind: Service
metadata:
  name: todolist-svc
  namespace: web
  labels:
    app: todolist
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30002
  selector:
    app: todolist
